version: '3.6'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: postgres
      # You can use whatever password you like
      POSTGRES_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - ./scripts/pgsql_init:/docker-entrypoint-initdb.d
      - ./scripts/data:/data
# Names our volume
volumes:
  my-db: